@RiverBooks.Web_HostAddress = http://localhost:5024

###
GET {{RiverBooks.Web_HostAddress}}/books/
Accept: application/json

###
GET {{RiverBooks.Web_HostAddress}}/books/19fce2dd-7e7a-49aa-8e73-f1780286a9e5
Accept: application/json

###
POST {{RiverBooks.Web_HostAddress}}/books
Accept: application/json
Content-Type: application/json
{
  "title" : "Modular Monoliths - Getting started",
  "author" : "Ardalis",
  "price" : 10.099,
  "description" : "So much fun !"
}

###
DELETE {{RiverBooks.Web_HostAddress}}/books/a965d81d-2632-47ea-b41d-450e485ebea0
Accept: application/json


###
PUT {{RiverBooks.Web_HostAddress}}/books/8f76bc5f-d903-44cb-8343-ead58bf75307/price
Accept: application/json
Content-Type: application/json
{
    "newPrice" : 14.099
}