// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RiverBooks.Books.Data.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Books")
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiverBooks.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books", "Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("733ba805-73cc-4f9c-9c23-2cd0e549b3f3"),
                            Author = "Jrr Tolkien",
                            Description = "Description book 1",
                            Price = 0.99m,
                            Title = "book1"
                        },
                        new
                        {
                            Id = new Guid("19fce2dd-7e7a-49aa-8e73-f1780286a9e5"),
                            Author = "Jrr Tolkien",
                            Description = "Description book 1",
                            Price = 1.99m,
                            Title = "book2"
                        },
                        new
                        {
                            Id = new Guid("f1b9b9f7-f300-48ef-b3b1-826211e3c319"),
                            Author = "Jrr Tolkien",
                            Description = "Description book 1",
                            Price = 2.99m,
                            Title = "book3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
